create or replace table jj_bd_additionalvalue (
   pk_additionalvalue   char(20)             not null,
   invclassname         char(100)            null,
   pk_invcl             char(20)             null,
   pk_invbasdoc         char(20)             null,
   invtype              char(50)             null,
   specdmin             number(20,8)         null,
   specdmax             number(20,8)         null,
   widthwmin            number(20,8)         null,
   widthwmax            number(20,8)         null,
   nadditionalvalue     number(20,8)         null,
   vmemo                varchar2(200)        null,
   ts                   char(19)             null,
   dr                   number(10)           null,
   vdef1                varchar2(20)         null,
   vdef2                varchar2(20)         null,
   vdef3                varchar2(20)         null,
   vdef4                varchar2(20)         null,
   vdef5                varchar2(20)         null,
   vdef6                varchar2(20)         null,
   vdef7                varchar2(20)         null,
   vdef8                varchar2(20)         null,
   vdef9                varchar2(20)         null,
   vdef10               varchar2(20)         null,
   constraint PK_JJ_BD_ADDITIONALVALUE primary key (pk_additionalvalue),
   constraint UN_JJ_BD_ADDITIONALVALUE unique (pk_invbasdoc)
);