  /***************************************************************\
  *     The skeleton of this class is generated by an automatic *
  * code generator for NC product. It is based on Velocity.     *
  \***************************************************************/
      	package nc.vo.ja.entityrecrpit;
   	
	import java.util.ArrayList;
	import nc.vo.pub.*;
	import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 *
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 *
 * 创建日期:2014-1-15
 * @author ${vmObject.author}
 * @version Your Project 1.0
 */
     public class JaEntityReceiptVO extends SuperVO {
           
             public String pk_corp;
             public String def5;
             public String def21;
             public Integer dr;
             public String voperatorid;
             public UFDate doreceiptdate;
             public String vapprovenote;
             public String receipttype;
             public String saletype;
             public String def7;
             public String def14;
             public String def27;
             public UFDateTime ts;
             public String def6;
             public String pk_custreceipt;
             public String def15;
             public String def18;
             public String def25;
             public UFDate def1;
             public String def23;
             public String def19;
             public String def20;
             public UFDate dmakedate;
             public String def29;
             public String receiptno;
             public String def17;
             public String def11;
             public String def22;
             public String pk_billtype;
             public Integer vbillstatus;
             public String def28;
             public String def30;
             public String doreceipttype;
             public String pk_busitype;
             public String def16;
             public String vbillno;
             public String def24;
             public String def10;
             public String def13;
             public String def8;
             public String vnote;
             public String pk_cumandoc;
             public UFDate dapprovedate;
             public String vapproveid;
             public String def2;
             public String def12;
             public String busstype;
             public String def4;
             public String pk_entity_receipt;
             public String def26;
             public String def3;
             public String def9;
             public String pk_custorder;
            
             public static final String  PK_CORP="pk_corp";   
             public static final String  DEF5="def5";   
             public static final String  DEF21="def21";   
             public static final String  DR="dr";   
             public static final String  VOPERATORID="voperatorid";   
             public static final String  DORECEIPTDATE="doreceiptdate";   
             public static final String  VAPPROVENOTE="vapprovenote";   
             public static final String  RECEIPTTYPE="receipttype";   
             public static final String  SALETYPE="saletype";   
             public static final String  DEF7="def7";   
             public static final String  DEF14="def14";   
             public static final String  DEF27="def27";   
             public static final String  TS="ts";   
             public static final String  DEF6="def6";   
             public static final String  PK_CUSTRECEIPT="pk_custreceipt";   
             public static final String  DEF15="def15";   
             public static final String  DEF18="def18";   
             public static final String  DEF25="def25";   
             public static final String  DEF1="def1";   
             public static final String  DEF23="def23";   
             public static final String  DEF19="def19";   
             public static final String  DEF20="def20";   
             public static final String  DMAKEDATE="dmakedate";   
             public static final String  DEF29="def29";   
             public static final String  RECEIPTNO="receiptno";   
             public static final String  DEF17="def17";   
             public static final String  DEF11="def11";   
             public static final String  DEF22="def22";   
             public static final String  PK_BILLTYPE="pk_billtype";   
             public static final String  VBILLSTATUS="vbillstatus";   
             public static final String  DEF28="def28";   
             public static final String  DEF30="def30";   
             public static final String  DORECEIPTTYPE="doreceipttype";   
             public static final String  PK_BUSITYPE="pk_busitype";   
             public static final String  DEF16="def16";   
             public static final String  VBILLNO="vbillno";   
             public static final String  DEF24="def24";   
             public static final String  DEF10="def10";   
             public static final String  DEF13="def13";   
             public static final String  DEF8="def8";   
             public static final String  VNOTE="vnote";   
             public static final String  PK_CUMANDOC="pk_cumandoc";   
             public static final String  DAPPROVEDATE="dapprovedate";   
             public static final String  VAPPROVEID="vapproveid";   
             public static final String  DEF2="def2";   
             public static final String  DEF12="def12";   
             public static final String  BUSSTYPE="busstype";   
             public static final String  DEF4="def4";   
             public static final String  PK_ENTITY_RECEIPT="pk_entity_receipt";   
             public static final String  DEF26="def26";   
             public static final String  DEF3="def3";   
             public static final String  DEF9="def9";   
             public static final String  PK_CUSTORDER="pk_custorder";   
      
    
        /**
	   * 属性pk_corp的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getPk_corp() {
		 return pk_corp;
	  }   
	  
     /**
	   * 属性pk_corp的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newPk_corp String
	   */
	public void setPk_corp(String newPk_corp) {
		
		pk_corp = newPk_corp;
	 } 	  
       
        /**
	   * 属性def5的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef5() {
		 return def5;
	  }   
	  
     /**
	   * 属性def5的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef5 String
	   */
	public void setDef5(String newDef5) {
		
		def5 = newDef5;
	 } 	  
       
        /**
	   * 属性def21的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef21() {
		 return def21;
	  }   
	  
     /**
	   * 属性def21的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef21 String
	   */
	public void setDef21(String newDef21) {
		
		def21 = newDef21;
	 } 	  
       
        /**
	   * 属性dr的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return Integer
	   */
	 public Integer getDr() {
		 return dr;
	  }   
	  
     /**
	   * 属性dr的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDr Integer
	   */
	public void setDr(Integer newDr) {
		
		dr = newDr;
	 } 	  
       
        /**
	   * 属性voperatorid的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getVoperatorid() {
		 return voperatorid;
	  }   
	  
     /**
	   * 属性voperatorid的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newVoperatorid String
	   */
	public void setVoperatorid(String newVoperatorid) {
		
		voperatorid = newVoperatorid;
	 } 	  
       
        /**
	   * 属性doreceiptdate的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return UFDate
	   */
	 public UFDate getDoreceiptdate() {
		 return doreceiptdate;
	  }   
	  
     /**
	   * 属性doreceiptdate的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDoreceiptdate UFDate
	   */
	public void setDoreceiptdate(UFDate newDoreceiptdate) {
		
		doreceiptdate = newDoreceiptdate;
	 } 	  
       
        /**
	   * 属性vapprovenote的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getVapprovenote() {
		 return vapprovenote;
	  }   
	  
     /**
	   * 属性vapprovenote的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newVapprovenote String
	   */
	public void setVapprovenote(String newVapprovenote) {
		
		vapprovenote = newVapprovenote;
	 } 	  
       
        /**
	   * 属性receipttype的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getReceipttype() {
		 return receipttype;
	  }   
	  
     /**
	   * 属性receipttype的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newReceipttype String
	   */
	public void setReceipttype(String newReceipttype) {
		
		receipttype = newReceipttype;
	 } 	  
       
        /**
	   * 属性saletype的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getSaletype() {
		 return saletype;
	  }   
	  
     /**
	   * 属性saletype的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newSaletype String
	   */
	public void setSaletype(String newSaletype) {
		
		saletype = newSaletype;
	 } 	  
       
        /**
	   * 属性def7的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef7() {
		 return def7;
	  }   
	  
     /**
	   * 属性def7的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef7 String
	   */
	public void setDef7(String newDef7) {
		
		def7 = newDef7;
	 } 	  
       
        /**
	   * 属性def14的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef14() {
		 return def14;
	  }   
	  
     /**
	   * 属性def14的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef14 String
	   */
	public void setDef14(String newDef14) {
		
		def14 = newDef14;
	 } 	  
       
        /**
	   * 属性def27的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef27() {
		 return def27;
	  }   
	  
     /**
	   * 属性def27的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef27 String
	   */
	public void setDef27(String newDef27) {
		
		def27 = newDef27;
	 } 	  
       
        /**
	   * 属性ts的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return UFDateTime
	   */
	 public UFDateTime getTs() {
		 return ts;
	  }   
	  
     /**
	   * 属性ts的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newTs UFDateTime
	   */
	public void setTs(UFDateTime newTs) {
		
		ts = newTs;
	 } 	  
       
        /**
	   * 属性def6的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef6() {
		 return def6;
	  }   
	  
     /**
	   * 属性def6的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef6 String
	   */
	public void setDef6(String newDef6) {
		
		def6 = newDef6;
	 } 	  
       
        /**
	   * 属性pk_custreceipt的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getPk_custreceipt() {
		 return pk_custreceipt;
	  }   
	  
     /**
	   * 属性pk_custreceipt的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newPk_custreceipt String
	   */
	public void setPk_custreceipt(String newPk_custreceipt) {
		
		pk_custreceipt = newPk_custreceipt;
	 } 	  
       
        /**
	   * 属性def15的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef15() {
		 return def15;
	  }   
	  
     /**
	   * 属性def15的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef15 String
	   */
	public void setDef15(String newDef15) {
		
		def15 = newDef15;
	 } 	  
       
        /**
	   * 属性def18的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef18() {
		 return def18;
	  }   
	  
     /**
	   * 属性def18的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef18 String
	   */
	public void setDef18(String newDef18) {
		
		def18 = newDef18;
	 } 	  
       
        /**
	   * 属性def25的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef25() {
		 return def25;
	  }   
	  
     /**
	   * 属性def25的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef25 String
	   */
	public void setDef25(String newDef25) {
		
		def25 = newDef25;
	 } 	  
       
        /**
	   * 属性def1的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public UFDate getDef1() {
		 return def1;
	  }   
	  
     /**
	   * 属性def1的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef1 String
	   */
	public void setDef1(UFDate newDef1) {
		
		def1 = newDef1;
	 } 	  
       
        /**
	   * 属性def23的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef23() {
		 return def23;
	  }   
	  
     /**
	   * 属性def23的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef23 String
	   */
	public void setDef23(String newDef23) {
		
		def23 = newDef23;
	 } 	  
       
        /**
	   * 属性def19的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef19() {
		 return def19;
	  }   
	  
     /**
	   * 属性def19的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef19 String
	   */
	public void setDef19(String newDef19) {
		
		def19 = newDef19;
	 } 	  
       
        /**
	   * 属性def20的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef20() {
		 return def20;
	  }   
	  
     /**
	   * 属性def20的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef20 String
	   */
	public void setDef20(String newDef20) {
		
		def20 = newDef20;
	 } 	  
       
        /**
	   * 属性dmakedate的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return UFDate
	   */
	 public UFDate getDmakedate() {
		 return dmakedate;
	  }   
	  
     /**
	   * 属性dmakedate的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDmakedate UFDate
	   */
	public void setDmakedate(UFDate newDmakedate) {
		
		dmakedate = newDmakedate;
	 } 	  
       
        /**
	   * 属性def29的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef29() {
		 return def29;
	  }   
	  
     /**
	   * 属性def29的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef29 String
	   */
	public void setDef29(String newDef29) {
		
		def29 = newDef29;
	 } 	  
       
        /**
	   * 属性receiptno的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getReceiptno() {
		 return receiptno;
	  }   
	  
     /**
	   * 属性receiptno的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newReceiptno String
	   */
	public void setReceiptno(String newReceiptno) {
		
		receiptno = newReceiptno;
	 } 	  
       
        /**
	   * 属性def17的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef17() {
		 return def17;
	  }   
	  
     /**
	   * 属性def17的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef17 String
	   */
	public void setDef17(String newDef17) {
		
		def17 = newDef17;
	 } 	  
       
        /**
	   * 属性def11的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef11() {
		 return def11;
	  }   
	  
     /**
	   * 属性def11的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef11 String
	   */
	public void setDef11(String newDef11) {
		
		def11 = newDef11;
	 } 	  
       
        /**
	   * 属性def22的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef22() {
		 return def22;
	  }   
	  
     /**
	   * 属性def22的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef22 String
	   */
	public void setDef22(String newDef22) {
		
		def22 = newDef22;
	 } 	  
       
        /**
	   * 属性pk_billtype的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getPk_billtype() {
		 return pk_billtype;
	  }   
	  
     /**
	   * 属性pk_billtype的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newPk_billtype String
	   */
	public void setPk_billtype(String newPk_billtype) {
		
		pk_billtype = newPk_billtype;
	 } 	  
       
        /**
	   * 属性vbillstatus的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return Integer
	   */
	 public Integer getVbillstatus() {
		 return vbillstatus;
	  }   
	  
     /**
	   * 属性vbillstatus的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newVbillstatus Integer
	   */
	public void setVbillstatus(Integer newVbillstatus) {
		
		vbillstatus = newVbillstatus;
	 } 	  
       
        /**
	   * 属性def28的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef28() {
		 return def28;
	  }   
	  
     /**
	   * 属性def28的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef28 String
	   */
	public void setDef28(String newDef28) {
		
		def28 = newDef28;
	 } 	  
       
        /**
	   * 属性def30的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef30() {
		 return def30;
	  }   
	  
     /**
	   * 属性def30的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef30 String
	   */
	public void setDef30(String newDef30) {
		
		def30 = newDef30;
	 } 	  
       
        /**
	   * 属性doreceipttype的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDoreceipttype() {
		 return doreceipttype;
	  }   
	  
     /**
	   * 属性doreceipttype的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDoreceipttype String
	   */
	public void setDoreceipttype(String newDoreceipttype) {
		
		doreceipttype = newDoreceipttype;
	 } 	  
       
        /**
	   * 属性pk_busitype的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getPk_busitype() {
		 return pk_busitype;
	  }   
	  
     /**
	   * 属性pk_busitype的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newPk_busitype String
	   */
	public void setPk_busitype(String newPk_busitype) {
		
		pk_busitype = newPk_busitype;
	 } 	  
       
        /**
	   * 属性def16的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef16() {
		 return def16;
	  }   
	  
     /**
	   * 属性def16的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef16 String
	   */
	public void setDef16(String newDef16) {
		
		def16 = newDef16;
	 } 	  
       
        /**
	   * 属性vbillno的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getVbillno() {
		 return vbillno;
	  }   
	  
     /**
	   * 属性vbillno的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newVbillno String
	   */
	public void setVbillno(String newVbillno) {
		
		vbillno = newVbillno;
	 } 	  
       
        /**
	   * 属性def24的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef24() {
		 return def24;
	  }   
	  
     /**
	   * 属性def24的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef24 String
	   */
	public void setDef24(String newDef24) {
		
		def24 = newDef24;
	 } 	  
       
        /**
	   * 属性def10的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef10() {
		 return def10;
	  }   
	  
     /**
	   * 属性def10的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef10 String
	   */
	public void setDef10(String newDef10) {
		
		def10 = newDef10;
	 } 	  
       
        /**
	   * 属性def13的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef13() {
		 return def13;
	  }   
	  
     /**
	   * 属性def13的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef13 String
	   */
	public void setDef13(String newDef13) {
		
		def13 = newDef13;
	 } 	  
       
        /**
	   * 属性def8的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef8() {
		 return def8;
	  }   
	  
     /**
	   * 属性def8的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef8 String
	   */
	public void setDef8(String newDef8) {
		
		def8 = newDef8;
	 } 	  
       
        /**
	   * 属性vnote的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getVnote() {
		 return vnote;
	  }   
	  
     /**
	   * 属性vnote的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newVnote String
	   */
	public void setVnote(String newVnote) {
		
		vnote = newVnote;
	 } 	  
       
        /**
	   * 属性pk_cumandoc的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getPk_cumandoc() {
		 return pk_cumandoc;
	  }   
	  
     /**
	   * 属性pk_cumandoc的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newPk_cumandoc String
	   */
	public void setPk_cumandoc(String newPk_cumandoc) {
		
		pk_cumandoc = newPk_cumandoc;
	 } 	  
       
        /**
	   * 属性dapprovedate的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return UFDate
	   */
	 public UFDate getDapprovedate() {
		 return dapprovedate;
	  }   
	  
     /**
	   * 属性dapprovedate的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDapprovedate UFDate
	   */
	public void setDapprovedate(UFDate newDapprovedate) {
		
		dapprovedate = newDapprovedate;
	 } 	  
       
        /**
	   * 属性vapproveid的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getVapproveid() {
		 return vapproveid;
	  }   
	  
     /**
	   * 属性vapproveid的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newVapproveid String
	   */
	public void setVapproveid(String newVapproveid) {
		
		vapproveid = newVapproveid;
	 } 	  
       
        /**
	   * 属性def2的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef2() {
		 return def2;
	  }   
	  
     /**
	   * 属性def2的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef2 String
	   */
	public void setDef2(String newDef2) {
		
		def2 = newDef2;
	 } 	  
       
        /**
	   * 属性def12的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef12() {
		 return def12;
	  }   
	  
     /**
	   * 属性def12的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef12 String
	   */
	public void setDef12(String newDef12) {
		
		def12 = newDef12;
	 } 	  
       
        /**
	   * 属性busstype的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getBusstype() {
		 return busstype;
	  }   
	  
     /**
	   * 属性busstype的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newBusstype String
	   */
	public void setBusstype(String newBusstype) {
		
		busstype = newBusstype;
	 } 	  
       
        /**
	   * 属性def4的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef4() {
		 return def4;
	  }   
	  
     /**
	   * 属性def4的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef4 String
	   */
	public void setDef4(String newDef4) {
		
		def4 = newDef4;
	 } 	  
       
        /**
	   * 属性pk_entity_receipt的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getPk_entity_receipt() {
		 return pk_entity_receipt;
	  }   
	  
     /**
	   * 属性pk_entity_receipt的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newPk_entity_receipt String
	   */
	public void setPk_entity_receipt(String newPk_entity_receipt) {
		
		pk_entity_receipt = newPk_entity_receipt;
	 } 	  
       
        /**
	   * 属性def26的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef26() {
		 return def26;
	  }   
	  
     /**
	   * 属性def26的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef26 String
	   */
	public void setDef26(String newDef26) {
		
		def26 = newDef26;
	 } 	  
       
        /**
	   * 属性def3的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef3() {
		 return def3;
	  }   
	  
     /**
	   * 属性def3的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef3 String
	   */
	public void setDef3(String newDef3) {
		
		def3 = newDef3;
	 } 	  
       
        /**
	   * 属性def9的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getDef9() {
		 return def9;
	  }   
	  
     /**
	   * 属性def9的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newDef9 String
	   */
	public void setDef9(String newDef9) {
		
		def9 = newDef9;
	 } 	  
       
        /**
	   * 属性pk_custorder的Getter方法.
	   *
	   * 创建日期:2014-1-15
	   * @return String
	   */
	 public String getPk_custorder() {
		 return pk_custorder;
	  }   
	  
     /**
	   * 属性pk_custorder的Setter方法.
	   *
	   * 创建日期:2014-1-15
	   * @param newPk_custorder String
	   */
	public void setPk_custorder(String newPk_custorder) {
		
		pk_custorder = newPk_custorder;
	 } 	  
       
       
    /**
	  * 验证对象各属性之间的数据逻辑正确性.
	  *
	  * 创建日期:2014-1-15
	  * @exception nc.vo.pub.ValidationException 如果验证失败,抛出
	  * ValidationException,对错误进行解释.
	 */
	 public void validate() throws ValidationException {
	
	 	ArrayList errFields = new ArrayList(); // errFields record those null

                                                      // fields that cannot be null.
       		  // 检查是否为不允许空的字段赋了空值,你可能需要修改下面的提示信息:
	
	   		if (pk_entity_receipt == null) {
			errFields.add(new String("pk_entity_receipt"));
			  }	
	   	
	    StringBuffer message = new StringBuffer();
		message.append("下列字段不能为空:");
		if (errFields.size() > 0) {
		String[] temp = (String[]) errFields.toArray(new String[0]);
		message.append(temp[0]);
		for ( int i= 1; i < temp.length; i++ ) {
			message.append(",");
			message.append(temp[i]);
		}
		throw new NullFieldException(message.toString());
		}
	 }
			   
       
   	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-1-15
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	  	 
	 	    return null;
	 	
	}   
    
    /**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-1-15
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	 	  return "pk_entity_receipt";
	 	}
    
	/**
      * <p>返回表名称.
	  * <p>
	  * 创建日期:2014-1-15
	  * @return java.lang.String
	 */
	public java.lang.String getTableName() {
				
		return "ja_entity_receipt";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-1-15
	  */
	public JaEntityReceiptVO() {
			
			   super();	
	  }    
    
            /**
	 * 使用主键进行初始化的构造子.
	 *
	 * 创建日期:2014-1-15
	 * @param newPk_entity_receipt 主键值
	 */
	 public JaEntityReceiptVO(String newPk_entity_receipt) {
		
		// 为主键字段赋值:
		 pk_entity_receipt = newPk_entity_receipt;
	
    	}
    
     
     /**
	  * 返回对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-1-15
	  * @return String
	  */
	   public String getPrimaryKey() {
				
		 return pk_entity_receipt;
	   
	   }

     /**
	  * 设置对象标识,用来唯一定位对象.
	  *
	  * 创建日期:2014-1-15
	  * @param newPk_entity_receipt  String    
	  */
	 public void setPrimaryKey(String newPk_entity_receipt) {
				
				pk_entity_receipt = newPk_entity_receipt; 
				
	 } 
           
	  /**
       * 返回数值对象的显示名称.
	   *
	   * 创建日期:2014-1-15
	   * @return java.lang.String 返回数值对象的显示名称.
	   */
	 public String getEntityName() {
				
	   return "ja_entity_receipt"; 
				
	 } 
} 
