/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.so;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2014-01-21 12:53:17
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class TaxInvoiceBbVO extends SuperVO {
	private java.lang.String ctaxinvoice_bid;
	private java.lang.String ctaxinvoice_bbid;
	private java.lang.String csourcebilltype = "32";
	private java.lang.String csourcebillid;
	private java.lang.String csourcebillrowid;
	private nc.vo.pub.lang.UFDate ddealdate;
	private nc.vo.pub.lang.UFDouble ndealnum;
	private nc.vo.pub.lang.UFDouble ndealmny;
	private java.lang.String cdealoper;
	private nc.vo.pub.lang.UFDouble nwriteinvoicenum;
	private nc.vo.pub.lang.UFDouble nwriteinvoicemny;
	private java.lang.String ctaxinvoiceid;
	private java.lang.Integer dr;
	private nc.vo.pub.lang.UFDateTime ts;

	public static final String CTAXINVOICE_BID = "ctaxinvoice_bid";
	public static final String CTAXINVOICE_BBID = "ctaxinvoice_bbid";
	public static final String CSOURCEBILLTYPE = "csourcebilltype";
	public static final String CSOURCEBILLID = "csourcebillid";
	public static final String CSOURCEBILLROWID = "csourcebillrowid";
	public static final String DDEALDATE = "ddealdate";
	public static final String NDEALNUM = "ndealnum";
	public static final String NDEALMNY = "ndealmny";
	public static final String CDEALOPER = "cdealoper";
	public static final String NWRITEINVOICENUM = "nwriteinvoicenum";
	public static final String NWRITEINVOICEMNY = "nwriteinvoicemny";
	public static final String CTAXINVOICEID = "ctaxinvoiceid";
			
	/**
	 * 属性ctaxinvoice_bid的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.String
	 */
	public java.lang.String getCtaxinvoice_bid () {
		return ctaxinvoice_bid;
	}   
	/**
	 * 属性ctaxinvoice_bid的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newCtaxinvoice_bid java.lang.String
	 */
	public void setCtaxinvoice_bid (java.lang.String newCtaxinvoice_bid ) {
	 	this.ctaxinvoice_bid = newCtaxinvoice_bid;
	} 	  
	/**
	 * 属性ctaxinvoice_bbid的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.String
	 */
	public java.lang.String getCtaxinvoice_bbid () {
		return ctaxinvoice_bbid;
	}   
	/**
	 * 属性ctaxinvoice_bbid的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newCtaxinvoice_bbid java.lang.String
	 */
	public void setCtaxinvoice_bbid (java.lang.String newCtaxinvoice_bbid ) {
	 	this.ctaxinvoice_bbid = newCtaxinvoice_bbid;
	} 	  
	/**
	 * 属性csourcebilltype的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.String
	 */
	public java.lang.String getCsourcebilltype () {
		return csourcebilltype;
	}   
	/**
	 * 属性csourcebilltype的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newCsourcebilltype java.lang.String
	 */
	public void setCsourcebilltype (java.lang.String newCsourcebilltype ) {
	 	this.csourcebilltype = newCsourcebilltype;
	} 	  
	/**
	 * 属性csourcebillid的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.String
	 */
	public java.lang.String getCsourcebillid () {
		return csourcebillid;
	}   
	/**
	 * 属性csourcebillid的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newCsourcebillid java.lang.String
	 */
	public void setCsourcebillid (java.lang.String newCsourcebillid ) {
	 	this.csourcebillid = newCsourcebillid;
	} 	  
	/**
	 * 属性csourcebillrowid的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.String
	 */
	public java.lang.String getCsourcebillrowid () {
		return csourcebillrowid;
	}   
	/**
	 * 属性csourcebillrowid的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newCsourcebillrowid java.lang.String
	 */
	public void setCsourcebillrowid (java.lang.String newCsourcebillrowid ) {
	 	this.csourcebillrowid = newCsourcebillrowid;
	} 	  
	/**
	 * 属性ddealdate的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return nc.vo.pub.lang.UFDate
	 */
	public nc.vo.pub.lang.UFDate getDdealdate () {
		return ddealdate;
	}   
	/**
	 * 属性ddealdate的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newDdealdate nc.vo.pub.lang.UFDate
	 */
	public void setDdealdate (nc.vo.pub.lang.UFDate newDdealdate ) {
	 	this.ddealdate = newDdealdate;
	} 	  
	/**
	 * 属性ndealnum的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getNdealnum () {
		return ndealnum;
	}   
	/**
	 * 属性ndealnum的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newNdealnum nc.vo.pub.lang.UFDouble
	 */
	public void setNdealnum (nc.vo.pub.lang.UFDouble newNdealnum ) {
	 	this.ndealnum = newNdealnum;
	} 	  
	/**
	 * 属性ndealmny的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getNdealmny () {
		return ndealmny;
	}   
	/**
	 * 属性ndealmny的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newNdealmny nc.vo.pub.lang.UFDouble
	 */
	public void setNdealmny (nc.vo.pub.lang.UFDouble newNdealmny ) {
	 	this.ndealmny = newNdealmny;
	} 	  
	/**
	 * 属性cdealoper的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.String
	 */
	public java.lang.String getCdealoper () {
		return cdealoper;
	}   
	/**
	 * 属性cdealoper的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newCdealoper java.lang.String
	 */
	public void setCdealoper (java.lang.String newCdealoper ) {
	 	this.cdealoper = newCdealoper;
	} 	  
	/**
	 * 属性nwriteinvoicenum的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getNwriteinvoicenum () {
		return nwriteinvoicenum;
	}   
	/**
	 * 属性nwriteinvoicenum的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newNwriteinvoicenum nc.vo.pub.lang.UFDouble
	 */
	public void setNwriteinvoicenum (nc.vo.pub.lang.UFDouble newNwriteinvoicenum ) {
	 	this.nwriteinvoicenum = newNwriteinvoicenum;
	} 	  
	/**
	 * 属性nwriteinvoicemny的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getNwriteinvoicemny () {
		return nwriteinvoicemny;
	}   
	/**
	 * 属性nwriteinvoicemny的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newNwriteinvoicemny nc.vo.pub.lang.UFDouble
	 */
	public void setNwriteinvoicemny (nc.vo.pub.lang.UFDouble newNwriteinvoicemny ) {
	 	this.nwriteinvoicemny = newNwriteinvoicemny;
	} 	  
	/**
	 * 属性ctaxinvoiceid的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.String
	 */
	public java.lang.String getCtaxinvoiceid () {
		return ctaxinvoiceid;
	}   
	/**
	 * 属性ctaxinvoiceid的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newCtaxinvoiceid java.lang.String
	 */
	public void setCtaxinvoiceid (java.lang.String newCtaxinvoiceid ) {
	 	this.ctaxinvoiceid = newCtaxinvoiceid;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2014-01-21 12:53:17
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2014-01-21 12:53:17
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
		return "ctaxinvoice_bid";
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2014-01-21 12:53:17
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "ctaxinvoice_bbid";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2014-01-21 12:53:17
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "so_taxinvoice_bb1";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2014-01-21 12:53:17
	  */
     public TaxInvoiceBbVO() {
		super();	
	}    
} 
