
/*
 * 毛边计算修改表结构  add by zhoujie 2010-09-27 09:41:40
 */
ALTER  TABLE IC_GENERAL_B ADD (
"GROSSPRICE"         	NUMBER(20,8) NULL,
"GROSSWEIGHT"       	NUMBER(20,8) NULL,
"GROSSSUMNY"         	NUMBER(20,8) NULL,
"STUFFPRICE"         	NUMBER(20,8) NULL,
"STUFFWEIGHT"        	NUMBER(20,8) NULL,
"STUFFSUMNY"        	NUMBER(20,8) NULL
)
