create table jj_scm_informationcost  (
   pk_informantioncost char(20),                         
   cbillid            char(20),
   vcosttype          varchar2(50),
   ccostunitid        char(20),
   vmemo              varchar2(200),
   ts                 char(19) default to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'),
   dr                 number(10),
   vdef1              varchar2(20),
   vdef2              varchar2(20),
   vdef3              varchar2(20),
   vdef4              varchar2(20),
   vdef5              varchar2(20),
   vdef6              varchar2(20),
   vdef7              varchar2(20),
   vdef8              varchar2(20),
   vdef9              varchar2(20),
   vdef10             varchar2(20),
   costcode           varchar2(40),
   costname           varchar2(200),
   currtypeid         char(20),
   cmeasdocid         char(20),
   nnumber            number(20,8),
   ntaxprice          number(20,8),
   noriginalcurtaxprice number(20,8),
   nprice             number(20,8),
   nmny               number(20,8),
   noriginalcurmny    number(20,8),
   nsummny            number(20,8),
   pk_taxitems        char(20),
   vtaxtype           varchar2(50),
   ninvoriginalcurmny number(20,8),
   ninvoriginalcurtaxmny number(20,8),
   ninvtaxmny         number(20,8),
   ninvmny            number(20,8),
   ninstoretaxmny     number(20,8),
   ninstoremny        number(20,8),
   ninstoreoriginalcurtaxmny number(20,8),
   ninstoreoriginalcurmny number(20,8),
   ismny char(1) default 'N' ,
   constraint PK_JJ_SCM_INFORMATIONCOST primary key (pk_informantioncost)
)