create table jj_bd_burrcoefficient (
   pk_burrcoefficient   char(20)             not null,
   invclassname         char(20)             null,
   pk_invcl             char(20)             null,
   pk_invbasdoc         char(20)             null,
   pk_cubasdoc          char(20)             null,
   nflash               number(20,3)         null,
   thkdmin              number(20,3)         null,
   thkdmax              number(20,3)         null,
   vmemo                varchar2(200)        null,
   ts                   char(19)             null,
   dr                   number(10)           null,
   vdef1                varchar2(20)         null,
   vdef2                varchar2(20)         null,
   vdef3                varchar2(20)         null,
   vdef4                varchar2(20)         null,
   vdef5                varchar2(20)         null,
   vdef6                varchar2(20)         null,
   vdef7                varchar2(20)         null,
   vdef8                varchar2(20)         null,
   vdef9                varchar2(20)         null,
   vdef10               varchar2(20)         null,
   constraint PK_JJ_BD_BURRCOEFFICIENT primary key (pk_burrcoefficient)
);