--请慎重使用,仅用于暂估处理执行模板回滚操作,只能回滚本补丁中内容.
delete from pub_billtemplet_b t where t.pk_billtemplet='40040503010000000000' and t.itemkey='cfycode';

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 5, '费用编码', '', 0, 1, 'cfybaseid->getColValue(bd_invmandoc,pk_invbasdoc,pk_invmandoc,cfeeid);cfyname->getColValue(bd_invbasdoc,invname,pk_invbasdoc,cfybaseid)', -1, 'cfeeid', 20, 'cfycode', 0, 'N', 1, 'Y', '', 0, '', '', '', 'N', 0, '<root><tab code="zgyf_table" showflag="N" listshowflag="N" /></root>', '40040503010000000000', '4004050301000000UZQV', '@@@@', 1, '<nc.ui.ps.estimate.FeeInvdocRef>', 'UC000-0003868', '', 'N', 1, 70, 'table', '暂估成本', 0, to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'), 'N', '', '', '', 1, 1, 'N', 1, '', 100);

delete from pub_billtemplet_b t where t.pk_billtemplet='40040503010000000000' and t.itemkey='cfeeid';

insert into pub_billtemplet_b (CARDFLAG, DATATYPE, DEFAULTSHOWNAME, DEFAULTVALUE, DR, EDITFLAG, EDITFORMULA, FOREGROUND, IDCOLNAME, INPUTLENGTH, ITEMKEY, ITEMTYPE, LEAFFLAG, LISTFLAG, LISTSHOWFLAG, LOADFORMULA, LOCKFLAG, METADATAPATH, METADATAPROPERTY, METADATARELATION, NEWLINEFLAG, NULLFLAG, OPTIONS, PK_BILLTEMPLET, PK_BILLTEMPLET_B, PK_CORP, POS, REFTYPE, RESID, RESID_TABNAME, REVISEFLAG, SHOWFLAG, SHOWORDER, TABLE_CODE, TABLE_NAME, TOTALFLAG, TS, USERDEFFLAG, USERDEFINE1, USERDEFINE2, USERDEFINE3, USEREDITFLAG, USERFLAG, USERREVISEFLAG, USERSHOWFLAG, VALIDATEFORMULA, WIDTH)
values (1, 0, 'cfeeid', '', 0, 1, '', -1, '', 20, 'cfeeid', 0, 'N', 1, 'N', 'cfybaseid->getColValue(bd_invmandoc,pk_invbasdoc,pk_invmandoc,cfeeid);cfyname->getColValue(bd_invbasdoc,invname,pk_invbasdoc,cfybaseid);cfycode->getColValue(bd_invbasdoc,invcode,pk_invbasdoc,cfybaseid)', 0, '', '', '', 'N', 0, '', '40040503010000000000', '4004050301000000UZQX', '@@@@', 1, '', '', '', 'N', 0, 70, 'table', '暂估成本', 0, to_char(sysdate,'yyyy-mm-dd hh24:mi:ss'), 'N', '', '', '', 1, 1, 'N', 1, '', 100);
