/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ic.jjvo;
	
import nc.vo.pub.*;
import nc.vo.pub.lang.*;
	
/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-12-22 10:42:10
 * @author MeiChao
 * @version NCPrj 1.0
 */
@SuppressWarnings("serial")
public class InvDetailCVO extends SuperVO {
	private String pk_mdcrk;
	private String pk_invdetail_c;
	private Integer dr;
	private String pk_invdetail;
	private String cgeneralbid;
	private UFDateTime ts;

	public static final String PK_MDCRK = "pk_mdcrk";
	public static final String PK_INVDETAIL_C = "pk_invdetail_c";
	public static final String PK_INVDETAIL = "pk_invdetail";
	public static final String CGENERALBID = "cgeneralbid";
			
	/**
	 * 属性pk_mdcrk的Getter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @return String
	 */
	public String getPk_mdcrk () {
		return pk_mdcrk;
	}   
	/**
	 * 属性pk_mdcrk的Setter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @param newPk_mdcrk String
	 */
	public void setPk_mdcrk (String newPk_mdcrk ) {
	 	this.pk_mdcrk = newPk_mdcrk;
	} 	  
	/**
	 * 属性pk_invdetail_c的Getter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @return String
	 */
	public String getPk_invdetail_c () {
		return pk_invdetail_c;
	}   
	/**
	 * 属性pk_invdetail_c的Setter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @param newPk_invdetail_c String
	 */
	public void setPk_invdetail_c (String newPk_invdetail_c ) {
	 	this.pk_invdetail_c = newPk_invdetail_c;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @return UFDouble
	 */
	public Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @param newDr UFDouble
	 */
	public void setDr (Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性pk_invdetail的Getter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @return String
	 */
	public String getPk_invdetail () {
		return pk_invdetail;
	}   
	/**
	 * 属性pk_invdetail的Setter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @param newPk_invdetail String
	 */
	public void setPk_invdetail (String newPk_invdetail ) {
	 	this.pk_invdetail = newPk_invdetail;
	} 	  
	/**
	 * 属性cgeneralbid的Getter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @return String
	 */
	public String getCgeneralbid () {
		return cgeneralbid;
	}   
	/**
	 * 属性cgeneralbid的Setter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @param newCgeneralbid String
	 */
	public void setCgeneralbid (String newCgeneralbid ) {
	 	this.cgeneralbid = newCgeneralbid;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @return UFDateTime
	 */
	public UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-12-22 10:42:10
	 * @param newTs UFDateTime
	 */
	public void setTs (UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-12-22 10:42:10
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-12-22 10:42:10
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_invdetail_c";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-12-22 10:42:10
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "SCM_INVDETAIL_C";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-12-22 10:42:10
	  */
     public InvDetailCVO() {
		super();	
	}    
} 
